version: '3'

services:

# Chat Service
  chat:
    build:
      context: chat_application/
      dockerfile: Dockerfile
    image: elc_chat_application
    container_name: chat_application
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - mongodb

# Notification Service
  notification:
    build:
      context: notif_application
      dockerfile: Dockerfile
    image: elc_notification_application
    container_name: notification_application
    ports:
      - '8001:8000'
    env_file:
      - .env
    depends_on:
      - mongodb

# MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
#    volumes:
#      - mongo_data:/data/db

# RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"